{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Untitled3.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "id": "si5dOY2AbOO5",
        "colab_type": "code",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "outputId": "47c95942-11a1-4163-959f-bd7ac1541094"
      },
      "source": [
        "!pip install python-telegram-bot\n",
        "!pip install adafruit-io\n",
        "from telegram.ext import Updater,CommandHandler,MessageHandler,Filters\n",
        "from Adafruit_IO import Client,Data\n",
        "import os\n",
        "\n",
        "def turnoffthelight(update, context):\n",
        "  context.bot.send_message(chat_id=update.effective_chat.id, text=\"Bulb turned off\")\n",
        "  context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://images.app.goo.gl/snsk3Yf7wh3pLnU17')\n",
        "  send_value(0)\n",
        "def turnonthelight(update, context):\n",
        "  context.bot.send_message(chat_id=update.effective_chat.id, text=\"Bulb turned on\")\n",
        "  context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://images.app.goo.gl/vxXurNQVAy5SevQWA')\n",
        "  send_value(1)\n",
        "\n",
        "def send_value(value):\n",
        "  feed = aio.feeds('sals')\n",
        "  aio.send_data(feed.key,value)\n",
        "\n",
        "def input_message(update, context):\n",
        "  text=update.message.text\n",
        "  if text == 'turnonthelight':\n",
        "    send_value(1)\n",
        "    context.bot.send_message(chat_id=update.effective_chat.id,text=\"Bulb turned on\")\n",
        "    context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://images.app.goo.gl/vxXurNQVAy5SevQWA')\n",
        "  elif text == 'turnoffthelight':\n",
        "    send_value(0)\n",
        "    context.bot.send_message(chat_id=update.effective_chat.id,text=\"Bulb turned off\")\n",
        "    context.bot.send_photo(chat_id=update.effective_chat.id,photo='https://images.app.goo.gl/snsk3Yf7wh3pLnU17')\n",
        "\n",
        "def start(update,context):\n",
        "  start_message='''\n",
        "/turnoff the light or 'turn off':To turn off the bulb ,sends value=0 in feed\n",
        "/turnon the light or 'turn on'  :To turn on the bulb ,sends value=1 in feed\n",
        "'''\n",
        "  context.bot.send_message(chat_id=update.effective_chat.id, text=start_message)\n",
        "\n",
        "ADAFRUIT_IO_USERNAME =  os.getenv('Sarahsals')\n",
        "ADAFRUIT_IO_KEY = os.getenv('aio_HRbW75Po7w7S1nTWlXhJ6qt2KsN7')\n",
        "TOKEN = os.getenv('1166498817:AAG4Uk1Ip_Ddpr6tlV_hsOFD_qkHy1jIrio')\n",
        "\n",
        "aio = Client('Sarahsals','aio_HRbW75Po7w7S1nTWlXhJ6qt2KsN7')\n",
        "updater=Updater('1166498817:AAG4Uk1Ip_Ddpr6tlV_hsOFD_qkHy1jIrio',use_context=True)\n",
        "dispatcher = updater.dispatcher\n",
        "dispatcher.add_handler(CommandHandler('turnoffthelight',turnoffthelight))\n",
        "dispatcher.add_handler(CommandHandler('turnonthelight',turnonthelight))\n",
        "dispatcher.add_handler(CommandHandler('start',start))\n",
        "dispatcher.add_handler(MessageHandler(Filters.text & (~Filters.command),input_message))\n",
        "updater.start_polling()\n",
        "updater.idle()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Collecting python-telegram-bot\n",
            "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/a6/2d/c72fc9a28144277f6170f2fcbfd3bd9427943497522b2689846596eb86cf/python_telegram_bot-12.8-py2.py3-none-any.whl (375kB)\n",
            "\r\u001b[K     |▉                               | 10kB 15.9MB/s eta 0:00:01\r\u001b[K     |█▊                              | 20kB 1.4MB/s eta 0:00:01\r\u001b[K     |██▋                             | 30kB 1.7MB/s eta 0:00:01\r\u001b[K     |███▌                            | 40kB 1.6MB/s eta 0:00:01\r\u001b[K     |████▍                           | 51kB 1.8MB/s eta 0:00:01\r\u001b[K     |█████▎                          | 61kB 2.0MB/s eta 0:00:01\r\u001b[K     |██████                          | 71kB 2.3MB/s eta 0:00:01\r\u001b[K     |███████                         | 81kB 2.5MB/s eta 0:00:01\r\u001b[K     |███████▉                        | 92kB 2.4MB/s eta 0:00:01\r\u001b[K     |████████▊                       | 102kB 2.5MB/s eta 0:00:01\r\u001b[K     |█████████▋                      | 112kB 2.5MB/s eta 0:00:01\r\u001b[K     |██████████▌                     | 122kB 2.5MB/s eta 0:00:01\r\u001b[K     |███████████▍                    | 133kB 2.5MB/s eta 0:00:01\r\u001b[K     |████████████▏                   | 143kB 2.5MB/s eta 0:00:01\r\u001b[K     |█████████████                   | 153kB 2.5MB/s eta 0:00:01\r\u001b[K     |██████████████                  | 163kB 2.5MB/s eta 0:00:01\r\u001b[K     |██████████████▉                 | 174kB 2.5MB/s eta 0:00:01\r\u001b[K     |███████████████▊                | 184kB 2.5MB/s eta 0:00:01\r\u001b[K     |████████████████▋               | 194kB 2.5MB/s eta 0:00:01\r\u001b[K     |█████████████████▌              | 204kB 2.5MB/s eta 0:00:01\r\u001b[K     |██████████████████▎             | 215kB 2.5MB/s eta 0:00:01\r\u001b[K     |███████████████████▏            | 225kB 2.5MB/s eta 0:00:01\r\u001b[K     |████████████████████            | 235kB 2.5MB/s eta 0:00:01\r\u001b[K     |█████████████████████           | 245kB 2.5MB/s eta 0:00:01\r\u001b[K     |█████████████████████▉          | 256kB 2.5MB/s eta 0:00:01\r\u001b[K     |██████████████████████▊         | 266kB 2.5MB/s eta 0:00:01\r\u001b[K     |███████████████████████▋        | 276kB 2.5MB/s eta 0:00:01\r\u001b[K     |████████████████████████▍       | 286kB 2.5MB/s eta 0:00:01\r\u001b[K     |█████████████████████████▎      | 296kB 2.5MB/s eta 0:00:01\r\u001b[K     |██████████████████████████▏     | 307kB 2.5MB/s eta 0:00:01\r\u001b[K     |███████████████████████████     | 317kB 2.5MB/s eta 0:00:01\r\u001b[K     |████████████████████████████    | 327kB 2.5MB/s eta 0:00:01\r\u001b[K     |████████████████████████████▉   | 337kB 2.5MB/s eta 0:00:01\r\u001b[K     |█████████████████████████████▊  | 348kB 2.5MB/s eta 0:00:01\r\u001b[K     |██████████████████████████████▌ | 358kB 2.5MB/s eta 0:00:01\r\u001b[K     |███████████████████████████████▍| 368kB 2.5MB/s eta 0:00:01\r\u001b[K     |████████████████████████████████| 378kB 2.5MB/s \n",
            "\u001b[?25hRequirement already satisfied: decorator>=4.4.0 in /usr/local/lib/python3.6/dist-packages (from python-telegram-bot) (4.4.2)\n",
            "Collecting cryptography\n",
            "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/c0/9c/647e559a6e8be493dc2a7a5d15d26cb501ca60ec299b356f23839a673a83/cryptography-3.1-cp35-abi3-manylinux2010_x86_64.whl (2.6MB)\n",
            "\u001b[K     |████████████████████████████████| 2.6MB 4.9MB/s \n",
            "\u001b[?25hRequirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.6/dist-packages (from python-telegram-bot) (5.1.1)\n",
            "Requirement already satisfied: certifi in /usr/local/lib/python3.6/dist-packages (from python-telegram-bot) (2020.6.20)\n",
            "Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.6/dist-packages (from cryptography->python-telegram-bot) (1.14.2)\n",
            "Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from cryptography->python-telegram-bot) (1.15.0)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi!=1.11.3,>=1.8->cryptography->python-telegram-bot) (2.20)\n",
            "Installing collected packages: cryptography, python-telegram-bot\n",
            "Successfully installed cryptography-3.1 python-telegram-bot-12.8\n",
            "Collecting adafruit-io\n",
            "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/ea/0b/5f2b24a13d283f3b523f6878b571a41618072c9af72a0f66f49745c4485b/adafruit-io-2.4.0.tar.gz (50kB)\n",
            "\u001b[K     |████████████████████████████████| 51kB 1.5MB/s \n",
            "\u001b[?25hRequirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from adafruit-io) (2.23.0)\n",
            "Collecting paho-mqtt\n",
            "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/59/11/1dd5c70f0f27a88a3a05772cd95f6087ac479fac66d9c7752ee5e16ddbbc/paho-mqtt-1.5.0.tar.gz (99kB)\n",
            "\u001b[K     |████████████████████████████████| 102kB 4.3MB/s \n",
            "\u001b[?25hRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->adafruit-io) (2020.6.20)\n",
            "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->adafruit-io) (1.24.3)\n",
            "Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->adafruit-io) (2.10)\n",
            "Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->adafruit-io) (3.0.4)\n",
            "Building wheels for collected packages: adafruit-io, paho-mqtt\n",
            "  Building wheel for adafruit-io (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for adafruit-io: filename=adafruit_io-2.4.0-cp36-none-any.whl size=20656 sha256=68690a53621fd526f7740d4e67912cc01a64ef4a8b2967bd8c02d3f256b35195\n",
            "  Stored in directory: /root/.cache/pip/wheels/05/e7/46/cd3dced11f962217204288f5faee41e56fbad8f7201f510619\n",
            "  Building wheel for paho-mqtt (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for paho-mqtt: filename=paho_mqtt-1.5.0-cp36-none-any.whl size=61415 sha256=792328432d7f98bb3df6ab62740e44adaca3562d34102b5f1105712f70b0a340\n",
            "  Stored in directory: /root/.cache/pip/wheels/02/94/6c/8474137cb7a5a3e001d70a22c8ff919caee69435376bccce79\n",
            "Successfully built adafruit-io paho-mqtt\n",
            "Installing collected packages: paho-mqtt, adafruit-io\n",
            "Successfully installed adafruit-io-2.4.0 paho-mqtt-1.5.0\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "stream",
          "text": [
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
            "No error handlers are registered, logging exception.\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 379, in _network_loop_retry\n",
            "    if not action_cb():\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/ext/updater.py\", line 340, in polling_action_cb\n",
            "    allowed_updates=allowed_updates)\n",
            "  File \"<decorator-gen-154>\", line 2, in get_updates\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 67, in decorator\n",
            "    result = func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/bot.py\", line 2138, in get_updates\n",
            "    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 333, in post\n",
            "    **urlopen_kwargs)\n",
            "  File \"/usr/local/lib/python3.6/dist-packages/telegram/utils/request.py\", line 248, in _request_wrapper\n",
            "    raise Conflict(message)\n",
            "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
          ],
          "name": "stderr"
        }
      ]
    }
  ]
}